pakhiwebsolutions/Controllers/AboutController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pakhiwebsolutions.Controllers
{
    public class AboutController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

pakhiwebsolutions/Controllers/ContactController.cs
using pakhiwebsolutions.Models;
using pakhiwebsolutions.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;

namespace pakhiwebsolutions.Controllers
{
    public class ContactController : Controller
    {
        private readonly IContactRepository _contactRepository;
        private readonly IWebHostEnvironment hostingEnvironment;
        private readonly AppDbContext _context;

        public ContactController(IContactRepository contactRepository, IWebHostEnvironment hostingEnvironment, AppDbContext context)
        {
            _contactRepository = contactRepository;
            this.hostingEnvironment = hostingEnvironment;
            _context = context;
        }
        [HttpPost]
        public JsonResult GetContactDetail(int ContactId)
        {
            Contact contact = _contactRepository.GetContact(ContactId);
            Contact newContact = new Contact
            {
                ContactId = contact.ContactId,
                FullName = contact.FullName,
                PhoneNo = contact.PhoneNo,
                EmailId = contact.EmailId,
                CompanyName = contact.CompanyName,
                RequirementDescription = contact.RequirementDescription
            };
            return Json(newContact);
            //FeesManagement.Models.Categerys.OBC
        }
        [HttpGet]
        public ViewResult Index()
        {
            var model = _contactRepository.GetAllContact();
            return View(model);
        }
        [HttpGet]
        [AllowAnonymous]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public IActionResult Create(ContactCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = ProcessUploadedFile(model);
                Contact newContact = new Contact
                {
                    FullName = model.FullName,
                    PhoneNo = model.PhoneNo,
                    EmailId = model.EmailId,
                    CompanyName = model.CompanyName,
                    RequirementDescription = model.RequirementDescription,
                    DocPath = uniqueFileName
                };
                _contactRepository.Add(newContact);
                RedirectToAction("index");
            }
            return View();

        }

        private string ProcessUploadedFile(ContactCreateViewModel model)
        {
            string uniqueFileName = null;
            if (model.DocPath != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "files");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.DocPath.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.DocPath.CopyTo(fileStream);
                }
            }

            return uniqueFileName;
        }

        [HttpGet]
        public ViewResult Edit(int ContactId)
        {
            Contact contact = _contactRepository.GetContact(ContactId);

            ContactEditViewModel contactEditViewModel = new ContactEditViewModel
            {
                FullName = contact.FullName,
                PhoneNo = contact.PhoneNo,
                EmailId = contact.EmailId,
                CompanyName = contact.CompanyName,
                RequirementDescription = contact.RequirementDescription,
                ExistingDocPath = contact.DocPath
            };
            return View(contactEditViewModel);
        }
        [HttpPost]
        public IActionResult Edit(ContactEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                Contact contact = _contactRepository.GetContact(model.ContactId);
                contact.FullName = model.FullName;
                contact.PhoneNo = model.PhoneNo;
                contact.EmailId = model.EmailId;
                contact.CompanyName = model.CompanyName;
                contact.RequirementDescription = model.RequirementDescription;
                if (model.DocPath != null)
                {
                    if (model.ExistingDocPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath, "files", model.ExistingDocPath);
                        System.IO.File.Delete(filePath);
                    }
                    contact.DocPath = ProcessUploadedFile(model);
                }
                Contact updateContact = _contactRepository.Update(contact);
                return RedirectToAction("index");
            }
            return View(model);

        }
        [HttpPost]
        public IActionResult Delete(int ContactId)
        {
            Contact contact = _contactRepository.GetContact(ContactId);

            if (contact == null)
            {
                Response.StatusCode = 404;
                return View("ContactNotFound", ContactId.ToString());
            }
            else
            {
                try
                {
                    Contact deleteContact = _contactRepository.Delete(contact.ContactId);
                    if (contact.DocPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath, "files", contact.DocPath);
                        System.IO.File.Delete(filePath);
                    }

                    return RedirectToAction("index");
                }
                catch (Exception ex)
                {

                }

            }
            return View("");

        }

    }
}

pakhiwebsolutions/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace pakhiwebsolutions.Controllers
{
    public class ServiceController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

pakhiwebsolutions/Views/Shared/NotFound.cshtml
@if (ViewBag.ErrorTitle == null)
{
    <h3>
        An occured while processing your request.
        The support team is notified and we are working on the fix.
    </h3>
    <h5>Please contact us on 9897505503</h5>
}
else
{
    <h1 class="text-danger">@ViewBag.ErrorTitle</h1>
    <h6 class="text-danger">@ViewBag.ErrorMessage</h6>
}

pakhiwebsolutions/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager;
<!DOCTYPE html>

<html>
<head>
    <!-- Google Tag Manager -->
    <script>
        (function (w, d, s, l, i) {
            w[l] = w[l] || []; w[l].push({
                'gtm.start':
                    new Date().getTime(), event: 'gtm.js'
            }); var f = d.getElementsByTagName(s)[0],
                j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
                    'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-PKS9WHP');</script>
    <!-- End Google Tag Manager -->
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="content-language" content="es">
    <environment include="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
        <link href="~/lib/twitter-bootstrap/css/site.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css"
              integrity="sha512-P5MgMn1jBN01asBgU0z60Qk4QxiXo86+wlFahKrsQf37c9cro517WzVSPPV1tDKzhku2iJ2FVgL67wG03SGnNA=="
              crossorigin="anonymous"
              asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              asp-suppress-fallback-integrity="true" />


        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
        <link href="~/lib/twitter-bootstrap/css/site.css" rel="stylesheet" />
    </environment>

    <title>
        @ViewBag.Title
    </title>
    <meta name="google-site-verification" content="q08CuqLbTeZ_kSpnUwc9pjCeJ8V7Tf6xwsastRdbjIA" />
    <meta name="description" content="@ViewBag.Description" />
    <meta name="keywords" content="@ViewBag.Keywords" />
    <meta name="author" content="Yogendra Kumar" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@700&display=swap" rel="stylesheet">
</head>
<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PKS9WHP"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->
    <div class="container">
        <div class="mt-5" style="color: #ff19cf;font-size: 36px;"><img src="~/files/Logo.png" width="70" height="70" alt="Logo" asp-append-version="true">Web Solutions</div>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" asp-controller="Contact" asp-action="index">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" id="navbarDropdownMenuLink" asp-controller="Service" asp-action="Index">
                            Services
                        </a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="navbarDropdownMenuLink" asp-controller="About" asp-action="Index">
                            About Us
                        </a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" id="navbarDropdownMenuLink" asp-controller="Contact" asp-action="Create">
                            Contact Us
                        </a>
                    </li>
                    @if (signInManager.IsSignedIn(User) && User.IsInRole("Administrator"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Contact Us
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Contact" asp-action="Create">Create</a>
                                <a class="dropdown-item" asp-controller="Contact" asp-action="Index">List</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Manage
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Administration" asp-action="ListUsers">Users</a>
                                <a class="dropdown-item" asp-controller="Administration" asp-action="ListRoles">Roles</a>
                            </div>
                        </li>
                    }

                </ul>
                <ul class="navbar-nav ml-auto">
                    @*If the user is signed-in display Logout link*@
                    @if (signInManager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <form method="post" asp-controller="account" asp-action="logout">
                                <button type="submit" style="width:auto" class="nav-link btn btn-link py-0">
                                    Logout @User.Identity.Name
                                </button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a asp-action="login" asp-controller="account" class="nav-link">Login</a>
                        </li>
                    }
                </ul>

            </div>


        </nav>
        <div>
            @RenderBody()
        </div>

    </div>

    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts", required: true)
    }

</body>
</html>